version: "3"

services:

  db:
    image: "mysql"
    # command: --default-authentication-plugin=mysql_native_password
    container_name: dbcontainer
   
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - dbdata:/var/lib/mysql
  
  admin:
    image: 'phpmyadmin'
    container_name: admincontainer
    restart: always
    ports:
      - 80:80
    expose:
      - '80'
    depends_on:
      - db

volumes:
  dbdata:
  
  # backend:
  #   build: .
  #   container_name: backendserver
  #   restart: always
  #   depends_on:
  #     - db